### ISSUE TITLE
不能抓取阅读数、点赞数、评论吗？

### ISSUE THREAD

**Issue by tonyxyl** [lqqyt2423/wechat_spider#1]
首先感谢你的代码，经测试能跑通。其次，由于对nodejs不熟悉，我想抓阅读、点赞、评论，抓包知道这些数据在哪，但我该从哪里着手改代码呢？谢谢。

**Comment by Jerryqun** [comment]
@tonyxyl  请问你解决了吗  我这边也是抓不到点赞和评论

**Comment by tonyxyl** [comment]
我用了其他方式解决，详见我的项目，https://github.com/tonyxyl/tools    wechat_parser.py部分
