### ISSUE TITLE
前台分类页面加载失败，一直在转圈

### ISSUE THREAD

**Issue by xitoe** [lqqyt2423/wechat_spider#11]
其他的都一切正常，代码看了好久，React看得优点晕哩呼噜的，不知道啥问题。
使用项目原先打包好的页面文件就出现这个问题了，应该不是我的问题...

请求支援！万分感谢~

**Comment by lqqyt2423** [comment]
分类页面不用管了 因为这个需要自己改数据库才会有的

**Comment by xitoe** [comment]
好的，谢谢~
