### ISSUE TITLE
本地WIN10调试

### ISSUE THREAD

**Issue by FuzongQiu** [lqqyt2423/wechat_spider#13]
项目都启动OK。
手机安装了CA证书，然后设置了代理，是内网的IP,此时不能上网了，是设置的有问题吗？

**Comment by cell13** [comment]
我试了下不需要安装证书，但是需要电脑和手机处于同一个局域网，并设置手机的代理为电脑IP：8101（默认）。抓取的时候程序看起来是正常跑的，但是没有或得到数据。

**Comment by lqqyt2423** [comment]
就是因为没有安装证书才会得不到数据呀
