### ISSUE TITLE
没有保存阅读量

### ISSUE THREAD

**Issue by zhiyue** [lqqyt2423/wechat_spider#16]
![image](https://user-images.githubusercontent.com/4208883/38804923-a2d61a68-41a6-11e8-8b43-9742d8e64ed1.png)
ui 没有显示阅读量
![image](https://user-images.githubusercontent.com/4208883/38804956-bf4fdfb2-41a6-11e8-8692-eb757a640fa7.png)

mongodb 里面也没有保存相应的数据

![image](https://user-images.githubusercontent.com/4208883/38804989-db6f1cb2-41a6-11e8-9cbd-9495494f6c8a.png)
console 里面有阅读量的输出

**Comment by lqqyt2423** [comment]
@zhiyue 原因为微信接口有所改变，已经修复此问题，请拉取最新代码

**Comment by duaisfn** [comment]
> @zhiyue 原因为微信接口有所改变，已经修复此问题，请拉取最新代码

您好 文章内容里的图片保存功能是不是没有做

**Comment by lqqyt2423** [comment]
没有保存图片的功能
