### ISSUE TITLE
手机在设置代理后浏览不了公众号的内容

### ISSUE THREAD

**Issue by angel-star** [lqqyt2423/wechat_spider#17]
手机在设置代理后浏览不了公众号的内容   ，并且在浏览网页的时候各种图片都是亮蓝色的 

可视化页面也没有数据进来，请问这是什么原因

**Comment by lqqyt2423** [comment]
@angel-star 默认设置替换了所有图片为一个小蓝色图片，加快网络速度。你浏览不了公众号文章内容，是解密https的证书没有正确安装，请查看文档安装好重试。

**Comment by angel-star** [comment]
@lqqyt2423 非常感谢你的耐心回复  已经可以正常使用了，谢谢，项目很棒。

**Comment by cell13** [comment]
证书是在什么目录，手机和电脑端都要安装吗

**Comment by klren0312** [comment]
PC和手机都安装了证书, 打开公众号还是报安全证书存在问题,,,

**Comment by klren0312** [comment]
> PC和手机都安装了证书, 打开公众号还是报安全证书存在问题,,,

https://github.com/avwo/whistle/issues/251#issuecomment-451713846
