### ISSUE TITLE
楼主这个好像运行有点问题

### ISSUE THREAD

**Issue by sishenlaoda** [lqqyt2423/wechat_spider#2]
楼主这个还能用吗，最近公司派我研究微信公众号文章爬取任务。我自己也想学习下具体的做法，可提供有偿服务。 QQ 460356696

**Comment by lqqyt2423** [comment]
可以用的

**Comment by stolennumber** [comment]
系统能跑起来，MongoDB中也有名为wecat_spider的db，但是里面没有数据，是哪个步骤错了嘛。我之前自己安装了anyproxy的，证书是否需要重新信任？

**Comment by wh4930188** [comment]
显示：DeprecationWarning: Calling an asynchronous function without callback is deprecated
