### ISSUE TITLE
能否增加黑名单、白名单模式？

### ISSUE THREAD

**Issue by halldong** [lqqyt2423/wechat_spider#23]
proxy开启常驻情况下，会爬取只是用来浏览的公众号。希望增加
- 黑名单：除名单内ID外，其余全部爬取
- 白名单：除名单内ID外，其余都不爬取。

谢谢。

**Comment by lqqyt2423** [comment]
https://github.com/lqqyt2423/wechat_spider/blob/a1c396bdce5fdeb4271e9735a934ebcb545db222/config.js#L94-L96

**Comment by haodong** [comment]
天呐，完美。谢谢！

**Comment by haodong** [comment]
我这样填了公号A和B的biz值`targetBiz: ['MzczTY0wMIxMNg==', 'Mz1NTINzk3czNw=='],`
但是在浏览公号C的时候，还是会抓取数据，请问是格式不对吗？

**Comment by lqqyt2423** [comment]
浏览了当然就会抓取
