### ISSUE TITLE
wx android 7.03 文章详情自动翻页失效

### ISSUE THREAD

**Issue by ensean** [lqqyt2423/wechat_spider#27]
rt, android7.0.3 文章详情页内置浏览器翻页不会自动翻页。选择某一篇文章从外部浏览器（chrome)打开可自行翻页，但无法获取read_sum #26

**Comment by ensean** [comment]
查了下 AnyProxy的日志，内置浏览器打开文章详情的时候，没有走如下的接口请求html了，使用外部浏览器打开的时候还保留有这个接口的请求，看着是7.0.3加的anti-spider机制。。
```
 /mp\.weixin\.qq\.com\/s\?__biz/
```

**Comment by zhaozhong** [comment]
我在安卓微信 6.7.3 中，文章详情页翻页正常， 公众号 profile 页无法自动翻页。在 ios 中两个页面的翻页都正常。

你的 profile 页可以自动翻页吗？

**Comment by ensean** [comment]
profile页正常自动翻页。

尝试了下从wx聊天对话框打开文章链接，发现文章详情页翻页正常，看来是wx漏了堵这个口子。。？
