### ISSUE TITLE
爬取所有历史文章的时候，没有获取到文章内容。

### ISSUE THREAD

**Issue by BolinWang** [lqqyt2423/wechat_spider#28]

**Comment by BolinWang** [comment]
爬取所有历史文章的时候，没有获取到文章内容

**Comment by yimun** [comment]
https://github.com/lqqyt2423/wechat_spider/pull/29 微信新版改了接口，这里修了

**Comment by LymphV** [comment]
现在微信的文章内容页anyproxy根本截不下来，怎么解决啊？

**Comment by BolinWang** [comment]
> #29 微信新版改了接口，这里修了

只能爬取l历史文章列表，并不能抓取所有文章正文啊

**Comment by Suley** [comment]
> > #29 微信新版改了接口，这里修了
> 
> 只能爬取l历史文章列表，并不能抓取所有文章正文啊

同，也不能抓取正文了。

**Comment by Suley** [comment]
> > > #29 微信新版改了接口，这里修了
> > 
> > 
> > 只能爬取l历史文章列表，并不能抓取所有文章正文啊
> 
> 同，也不能抓取正文了。

自己手动刷新一下文章详情页面，就好了

**Comment by ritou11** [comment]
1. 在公众号详情->全部消息页面爬取历史文章列表
2. 在获得历史文章列表后，打开任一篇推送即可自动爬取历史文章内容
3. 有时因为微信的缓存等问题，打开推送后不开始爬取，此时手动刷新即可
