### ISSUE TITLE
页面数据 不能抓取了！！....

### ISSUE THREAD

**Issue by iexe** [lqqyt2423/wechat_spider#34]
页面数据 不能抓取了！！....包括 内容 阅读数 等数据

**Comment by iexe** [comment]
我重新git clone https://github.com/lqqyt2423/wechat_spider.git 安装的时候也提示出错
目前 列表页面正常爬取 只是不会进行内容页面的爬取，
之前如果点击进入某个文章页面的时候会自动获取到阅读量 目前失效
我最近一次正常使用是在 4月22日
在VM虚拟机环境下的ubuntu中运行的此安装程的爬取环境 上个月使用过后暂停虚拟机直至今日，发现功能失效！
感谢开源这么好用的软件！谢谢

**Comment by ritou11** [comment]
不能爬取、安装提示出错。。。。可能性太多了，贴出具体的问题还可以研究研究

另外你的问题可能在[这里](https://github.com/lqqyt2423/wechat_spider/pull/29#issuecomment-493765862)得到解决。

**Comment by lqqyt2423** [comment]
用低版本的微信试试。或者不要从推送列表打开文章，从公众号历史记录页面打开文章试试。

**Comment by iexe** [comment]
谢谢，我觉得，低版本微信会对我有帮助


 
---原始邮件---
发件人: "liqiang"<notifications@github.com>
发送时间: 2019年5月24日(星期五) 上午10:04
收件人: "lqqyt2423/wechat_spider"<wechat_spider@noreply.github.com>;
抄送: "南墙"<info@iiexe.com>;"Author"<author@noreply.github.com>;
主题: Re: [lqqyt2423/wechat_spider] 页面数据 不能抓取了！！.... (#34)



用低版本的微信试试。或者不要从推送列表打开文章，从公众号历史记录页面打开文章试试。

**Comment by xujun05** [comment]
> 用低版本的微信试试。或者不要从推送列表打开文章，从公众号历史记录页面打开文章试试。

目前微信7.0.4版本 page这个rule无法执行，不跳转。
