### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by anthonysun0726** [lqqyt2423/wechat_spider#39]
13 verbose stack Error: wechat_spider@1.1.1 start: `DEBUG=ws:* NODE_ENV=production node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Anthony.sun\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Anthony.sun\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid wechat_spider@1.1.1
15 verbose cwd C:\Users\Anthony.sun\Documents\OneDrive - Dana Incorporated\Anthony\python\wechat_spider
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Anthony.sun\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.7.0
19 verbose npm  v6.10.2
20 error code ELIFECYCLE
21 error errno 1
22 error wechat_spider@1.1.1 start: `DEBUG=ws:* NODE_ENV=production node index.js`
22 error Exit status 1
23 error Failed at the wechat_spider@1.1.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by enjustli** [comment]
PS G:\Test\wechat_spider-master> npm start                                                                       
> wechat_spider@1.1.1 start G:\Test\wechat_spider-master
> DEBUG=ws:* NODE_ENV=production node index.js

'DEBUG' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wechat_spider@1.1.1 start: `DEBUG=ws:* NODE_ENV=production node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wechat_spider@1.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\justLi\AppData\Roaming\npm-cache\_logs\2019-10-13T12_44_38_324Z-debug.log

**Comment by lqqyt2423** [comment]
拉去最新的代码吧。
这个问题应该是 win 上设置环境变量的方法不一样。
你直接运行 node index.js 命令应该可以
