### ISSUE TITLE
公众号文章列表已经不可以爬取

### ISSUE THREAD

**Issue by xujun05** [lqqyt2423/wechat_spider#40]
列表文章无法爬取。

**Comment by lanhyan** [comment]
> 列表文章无法爬取。

我最近才使用这个项目的，我也发现历史消息页面不可以爬取了。我在我这边的环境中发现是加载历史消息的页面中的某些数据应该是改成异步加载了，我在历史消息页面的注入中加入判断数据是否加载完的操作后发现就可以正常爬取了，我把我的修改向这个项目提了一个pull request了，你可以看下照这个pull request修改之后能否正常爬取。
https://github.com/lqqyt2423/wechat_spider/pull/41

**Comment by lqqyt2423** [comment]
用旧版本微信，或自己拼接旧版本的微信历史页面链接打开。
