### ISSUE TITLE
centos7下docker安装，AnyProxy报错

### ISSUE THREAD

**Issue by qingfengfenga** [lqqyt2423/wechat_spider#44]
全部默认只改了mongodb路径
使用公网ip，可以访问8104端口，访问8101端口报错，下面是报错内容

<img width="563" alt="WX20200214-125216@2x" src="https://user-images.githubusercontent.com/41416092/74502831-beb4e100-4f29-11ea-9721-d904b4a26c79.png">

**Comment by lqqyt2423** [comment]
8101端口本就不能直接http访问，这个端口是你设置代理的端口
