### ISSUE TITLE
will forward to local https server，然后网络错误

### ISSUE THREAD

**Issue by ttc9082** [lqqyt2423/wechat_spider#5]
received https CONNECT request p54-keyvalueservice.icloud.com
==>will bypass the man-in-the-middle proxy

received https CONNECT request mp.weixin.qq.com
==>will forward to local https server
[internal https]proxy server for mp.weixin.qq.com established

received https CONNECT request mp.weixin.qq.com
==>will forward to local https server
[internal https]proxy server for mp.weixin.qq.com established

received https CONNECT request mp.weixin.qq.com
==>will forward to local https server

然后就没反应了，微信上显示的是网络错误。

**Comment by lqqyt2423** [comment]
按照anyproxy 文档装证书
