### ISSUE TITLE
抓取完不会停止

### ISSUE THREAD

**Issue by 52Lau** [lqqyt2423/wechat_spider#51]
![image](https://user-images.githubusercontent.com/37538641/77634271-a524a180-6f8b-11ea-9ecf-1ccf804e7196.png)

![image](https://user-images.githubusercontent.com/37538641/77634186-86260f80-6f8b-11ea-84a5-1a086ef330ae.png)

前面的已经爬取完毕了,一直在刷新这几条(最近的这10条)

**Comment by lqqyt2423** [comment]
这是 feature 不是 bug :)

**Comment by 52Lau** [comment]
哦,

**Comment by 52Lau** [comment]
这个是完善了么
