### ISSUE TITLE
'DEBUG' 不是内部或外部命令，也不是可运行的程序是为什么？

### ISSUE THREAD

**Issue by onepiecelyk** [lqqyt2423/wechat_spider#7]
npm start

> wechat_spider@1.1.0 start E:\study\weixin\wechat_spider
> DEBUG=wechat_spider:* nodemon index.js --ignore client/

'DEBUG' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by lqqyt2423** [comment]
试试`set DEBUG=wechat_spider:* nodemon index.js --ignore client/`
可能windows 会不一样
我也没试过 你也可以直接`node index.js` 代替`npm start`
@onepiecelyk

**Comment by AggiWang** [comment]
我也是这个问题，win10遇到的，请问你最后是怎么解决的？ @onepiecelyk @lqqyt2423

**Comment by cell13** [comment]
> 
> 
> 我也是这个问题，win10遇到的，请问你最后是怎么解决的？ @onepiecelyk @lqqyt2423
@lqqyt2423 前面说了可以使用下面的命令替代，npm start，亲测可以使用
node index.js
